### ISSUE TITLE
Libcairo cannot be installed

### ISSUE THREAD

**Issue by kijk2869** [koreanbots/py-sdk#3]
```python
Traceback (most recent call last):
  File "bot.py", line 26, in <module>
    import koreanbots
  File "C:\Users\water\AppData\Local\Programs\Python\Python38\lib\site-packages\koreanbots\__init__.py", line 16, in <module>
    from .client import Client
  File "C:\Users\water\AppData\Local\Programs\Python\Python38\lib\site-packages\koreanbots\client.py", line 28, in <module>
    from .http import HTTPClient
  File "C:\Users\water\AppData\Local\Programs\Python\Python38\lib\site-packages\koreanbots\http.py", line 31, in <module>
    from cairosvg import svg2png
  File "C:\Users\water\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\__init__.py", line 42, in <module>
    from . import surface  # noqa isort:skip
  File "C:\Users\water\AppData\Local\Programs\Python\Python38\lib\site-packages\cairosvg\surface.py", line 25, in <module>
    import cairocffi as cairo
  File "C:\Users\water\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 48, in <module>
    cairo = dlopen(
  File "C:\Users\water\AppData\Local\Programs\Python\Python38\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```

**Comment by kijk2869** [comment]
> 이슈를 남겨주셔서 감사합니다!
> 곧 처리될테니 침착하게 기다려주세요!

@wonderlandpark  고쳤다메
