### ISSUE TITLE
x-ratelimit-remaining 값을 찾을 수 없음

### ISSUE THREAD

**Issue by Craphting** [koreanbots/py-sdk#31]
Traceback (most recent call last):
  .
  .
  .
    if (await self.bot.koreanbots.is_voted(ctx.author.id, self.bot.user.id)).voted is True:
  File "C:\Users\Administrator\Desktop\Bots\Ark\Ark\lib\site-packages\koreanbots\client.py", line 183, in is_voted
    return KoreanbotsVote(**await self.get_user_vote(user_id, bot_id))
  File "C:\Users\Administrator\Desktop\Bots\Ark\Ark\lib\site-packages\koreanbots\http.py", line 31, in decorator_function
    return await f(self, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\Bots\Ark\Ark\lib\site-packages\koreanbots\http.py", line 247, in get_user_vote
    return await self.request(
  File "C:\Users\Administrator\Desktop\Bots\Ark\Ark\lib\site-packages\koreanbots\http.py", line 116, in request
    remain_limit = response.headers["x-ratelimit-remaining"]
KeyError: 'x-ratelimit-remaining'

**Comment by SaidBySolo** [comment]
@koreanbots/core-developer

**Comment by wonderlandpark** [comment]
해더가 누락된 것인지 요청에 실패하여 해당 올 가 발생했는지 정확한 정보가 필요할 것 같습니다

**Comment by Craphting** [comment]
> 해더가 누락된 것인지 요청에 실패하여 해당 오류가 발생했는지 정확한 정보가 필요할 것 같습니다

이후에는 정상적으로 작동하였으니 아마 임시적으로 요청에 실패한 게 맞는 것 같습니다.
